[package]
name = "flize"
version = "3.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/xacrimon/flize"
homepage = "https://github.com/xacrimon/flize"
description = "non global, configurable and fast concurrent resource reclamation"
readme = "README.md"
documentation = "https://docs.rs/flize"
keywords = ["atomic", "concurrent", "memory", "epoch", "reclamation"]
categories = ["concurrency", "algorithms", "data-structures"]

[dependencies]
generic-array = "0.14.4"
once_cell = { version = "1.4.0" }
